version: "3"

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nuguna
      MYSQL_DATABASE: nuguna
    ports:
      - "33060:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d:cached

  xe:
    depends_on:
      - db
    build: ./
    ports:
      - "8888:80"
    restart: always
    volumes:
      - ./docroot:/var/www/html:cached
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/db.config.php:/var/www/html/files/config/db.config.php
